In [1]:
import pandas as pd

In [2]:
df_most_relevants = pd.read_csv('../../data/llm_juris_tcu/eval_most_relevants.csv')
df_most_relevants

,QUERY_ID,RANK,DOC_ID,ENGINE,QUERY_TEXT,DOC_TEXT,LLM_SCORE,LLM_REASONING
0,1,1,21064,(BM25|STS)+Reranker,técnica e preço,Admite-se a preponderância da técnica sobre o ...,3.0,O enunciado aborda diretamente a relação entre...
1,72,2,21064,(BM25|STS)+Reranker,ponderação técnica e preço,Admite-se a preponderância da técnica sobre o ...,3.0,"O enunciado aborda diretamente a consulta, tra..."
2,1,2,42166,(BM25|STS)+Reranker,técnica e preço,Diante da complexidade e da natureza do objeto...,3.0,"O enunciado aborda diretamente a consulta, men..."
3,111,8,42166,(BM25|STS)+Reranker,Qual é a modalidade de licitação utilizada par...,Diante da complexidade e da natureza do objeto...,2.0,O enunciado aborda a modalidade de licitação '...
4,1,3,13702,(BM25|STS)+Reranker,técnica e preço,"Nas licitações do tipo técnica e preço, é irre...",3.0,O enunciado aborda diretamente a consulta sobr...
...,...,...,...,...,...,...,...,...
1495,100,1,17892,(BM25|STS)+Reranker,assistência médica a servidores,A contratação de entidade para prestação de se...,2.0,O enunciado aborda a contratação de entidade p...
1496,150,1,17892,(BM25|STS)+Reranker,Qual é a regra geral para a contratação de ent...,A contratação de entidade para prestação de se...,3.0,"O enunciado responde diretamente à pergunta, m..."
1497,106,7,17267,(BM25|STS)+Reranker,O pregão é adequado para concessões de uso de ...,No âmbito das concessões realizadas pela Agênc...,1.0,O enunciado está relacionado ao tópico de conc...
1498,150,8,91180,(BM25|STS)+Reranker,Qual é a regra geral para a contratação de ent...,É possível a contratação da execução indireta ...,1.0,O enunciado de jurisprudência aborda a contrat...
1499,144,7,27083,(BM25|STS)+Reranker,A prescrição da pretensão punitiva do TCU afet...,A imprescritibilidade das ações de ressarcimen...,1.0,O enunciado de jurisprudência aborda a impresc...

In [8]:
df_stats = df_most_relevants.groupby(['QUERY_ID', 'LLM_SCORE']).count()[['DOC_ID']]
df_stats.columns = ['COUNT']
df_stats = df_stats.reset_index()
df_stats = df_stats.set_index('QUERY_ID')
df_stats = df_stats.astype({'LLM_SCORE': 'int32'})
df_stats

          LLM_SCORE  COUNT
QUERY_ID
1                 3     10
2                 0      3
2                 1      2
2                 2      2
2                 3      3
...             ...    ...
149               2      4
149               3      4
150               1      2
150               2      3
150               3      5

[355 rows x 2 columns]

In [9]:
df_stats['SCORE_3'] = df_stats.query('LLM_SCORE == 3')['COUNT']
df_stats['SCORE_2'] = df_stats.query('LLM_SCORE == 2')['COUNT']
df_stats['SCORE_1'] = df_stats.query('LLM_SCORE == 1')['COUNT']
df_stats['SCORE_0'] = df_stats.query('LLM_SCORE == 0')['COUNT']
df_stats = df_stats.fillna('0')
del df_stats['LLM_SCORE']
del df_stats['COUNT']
df_stats = df_stats.astype({'SCORE_3': 'int32', 'SCORE_2': 'int32', 'SCORE_1': 'int32', 'SCORE_0': 'int32'})
df_stats = df_stats.drop_duplicates()
df_stats['TOTAL'] = df_stats['SCORE_3'] + df_stats['SCORE_2'] + df_stats['SCORE_1'] + df_stats['SCORE_0'] 
df_stats

          SCORE_3  SCORE_2  SCORE_1  SCORE_0  TOTAL
QUERY_ID
1              10        0        0        0     10
2               3        2        2        3     10
3               6        4        0        0     10
8               7        2        1        0     10
9               8        2        0        0     10
10              9        1        0        0     10
11              2        8        0        0     10
14              5        5        0        0     10
15              4        6        0        0     10
16              3        7        0        0     10
17              2        6        2        0     10
20              3        2        4        1     10
26              4        5        1        0     10
28              1        9        0        0     10
29              5        1        4        0     10
30              7        3        0        0     10
31              5        4        1        0     10
32              8        1        1        0     10
34              1        6        3        0     10
37              0        4        6        0     10
44              7        1        0        2     10
47              3        5        2        0     10
55              3        4        3        0     10
56              2        3        5        0     10
57              1        3        6        0     10
62              2        2        6        0     10
64              9        0        1        0     10
68              1        0        4        5     10
69              6        2        2        0     10
75              3        2        5        0     10
79              2        4        4        0     10
81              2        1        6        1     10
82              1        2        5        2     10
83              0        9        1        0     10
84              1        8        1        0     10
85              3        6        1        0     10
86              6        3        1        0     10
91              1        0        9        0     10
96              1        5        4        0     10
97              1        2        7        0     10
98              6        1        3        0     10
106             1        4        5        0     10
112             2        4        3        1     10
129             2        7        0        1     10
131             3        3        4        0     10
133             1        7        2        0     10
141             1        0        6        3     10
142             2        1        2        5     10
144             7        1        2        0     10
145             8        0        2        0     10
149             4        4        2        0     10
150             5        3        2        0     10

In [10]:
df_stats.to_csv('../../data/llm_juris_tcu/eval_statistics.csv')

In [11]:
df_most_relevants

,QUERY_ID,RANK,DOC_ID,ENGINE,QUERY_TEXT,DOC_TEXT,LLM_SCORE,LLM_REASONING
0,1,1,21064,(BM25|STS)+Reranker,técnica e preço,Admite-se a preponderância da técnica sobre o ...,3.0,O enunciado aborda diretamente a relação entre...
1,72,2,21064,(BM25|STS)+Reranker,ponderação técnica e preço,Admite-se a preponderância da técnica sobre o ...,3.0,"O enunciado aborda diretamente a consulta, tra..."
2,1,2,42166,(BM25|STS)+Reranker,técnica e preço,Diante da complexidade e da natureza do objeto...,3.0,"O enunciado aborda diretamente a consulta, men..."
3,111,8,42166,(BM25|STS)+Reranker,Qual é a modalidade de licitação utilizada par...,Diante da complexidade e da natureza do objeto...,2.0,O enunciado aborda a modalidade de licitação '...
4,1,3,13702,(BM25|STS)+Reranker,técnica e preço,"Nas licitações do tipo técnica e preço, é irre...",3.0,O enunciado aborda diretamente a consulta sobr...
...,...,...,...,...,...,...,...,...
1495,100,1,17892,(BM25|STS)+Reranker,assistência médica a servidores,A contratação de entidade para prestação de se...,2.0,O enunciado aborda a contratação de entidade p...
1496,150,1,17892,(BM25|STS)+Reranker,Qual é a regra geral para a contratação de ent...,A contratação de entidade para prestação de se...,3.0,"O enunciado responde diretamente à pergunta, m..."
1497,106,7,17267,(BM25|STS)+Reranker,O pregão é adequado para concessões de uso de ...,No âmbito das concessões realizadas pela Agênc...,1.0,O enunciado está relacionado ao tópico de conc...
1498,150,8,91180,(BM25|STS)+Reranker,Qual é a regra geral para a contratação de ent...,É possível a contratação da execução indireta ...,1.0,O enunciado de jurisprudência aborda a contrat...
1499,144,7,27083,(BM25|STS)+Reranker,A prescrição da pretensão punitiva do TCU afet...,A imprescritibilidade das ações de ressarcimen...,1.0,O enunciado de jurisprudência aborda a impresc...

In [12]:
df_most_relevants.to_csv('../../data/llm_juris_tcu/eval_most_relevants.csv', index=False)